//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdvance.WebShoppingOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FId { get; set; }
        public string FTitle { get; set; }
        public string FContent { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
